[platformio]
src_dir = examples/BTHomeScan

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_deps =
	https://github.com/bblanchon/ArduinoJson
	file://src
build_type = debug
build_flags =
	-g
	-DCORE_DEBUG_LEVEL=2
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:esp32dev]
board = esp32dev
upload_speed = 1500000

[env:m5stamp-s3]
board = m5stack-stamps3
debug_tool = esp-builtin

[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6


